import Link from "next/link";
import { ArrowRight,ArrowUpRight,Clock3,House,BriefcaseBusiness,WandSparkles } from "lucide-react";
import { ResourceFilter } from "@/components/resource-filter";
import { CATEGORIES,getGuideCards,showsUnpublished,type Guide,type GuideIcon } from "@/lib/guides";
// Cards are built from the guide files in content/guides/ (see lib/guides.ts).
const icons:Record<GuideIcon,typeof House>={house:House,briefcase:BriefcaseBusiness,wand:WandSparkles,clock:Clock3};
// Published: "Read the guide", and the whole card opens the guide (the link stretches over the card).
// Not published: "Guide coming soon", not clickable. On Preview only, an extra "Internal preview" link for review.
function CardLink({guide}:{guide:Guide}){const href=`/resources/${guide.slug}`;if(guide.status==="published")return <Link href={href} className="resource-read">Read the guide <ArrowRight size={15} aria-hidden="true"/></Link>;return <span className="resource-cta"><span className="resource-soon">Guide coming soon</span>{showsUnpublished()&&<Link href={href} className="resource-preview-tag" aria-label={`Internal preview of ${guide.title} (not public)`}>Internal preview</Link>}</span>}
export default function Resources(){const guides=getGuideCards();return <main><section className="page-hero shell"><p className="eyebrow">The practical library</p><h1>Useful first.<br/><em>Always.</em></h1><p>Short, clear guides for doing ordinary things a little more easily with AI. Pick a problem—not a platform.</p></section><section className="resource-section shell"><ResourceFilter filters={[...CATEGORIES]} cards={guides.map((g,i)=>{const Icon=icons[g.icon];return {category:g.category,card:<article className={`resource-card resource-${i%4+1}${g.status==="published"?" is-linked":""}`} key={g.slug}><Icon/><div><span className="pill">{g.label}</span><h2>{g.title}</h2><p>{g.summary}</p></div><div className="resource-meta"><span>{g.readingTime} min read</span><CardLink guide={g}/></div></article>}})} empty={<div className="resource-empty"><h2>Tools are coming.</h2><p>We&apos;re testing useful AI tools and adding the ones genuinely worth knowing about.</p><p>Join the Sunday Edit to hear when new guides arrive.</p><Link href="/newsletter#signup" className="button button-primary">Join the Sunday Edit <ArrowUpRight size={17}/></Link></div>}/></section><section className="mini-cta shell"><p className="eyebrow light">Not sure where to begin?</p><h2>Start with one small win.</h2><p>Our free weekly edit gives you one useful thing to try—not fifty things to catch up on.</p><Link href="/newsletter#signup" className="button button-light">Join the Sunday Edit <ArrowUpRight size={17}/></Link></section></main>}
